config/routes.rb
Rails.application.routes.draw do

  resources :friends 
  
  get 'weather' => 'weather#show'

  root 'friends#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

	def index
		@friends = Friend.all
	end

	def edit
		@friend = Friend.find(params["id"])
	end

	def update
		@friend = Friend.find(params[:id])
	  	if @friend.update(friend_params)
	    	redirect_to friends_path
	  	else
	    	render 'edit'
	  	end
	end

	def create
		@friend = Friend.new(friend_params)
		@friend.save
  		redirect_to friends_path
	end

	def destroy 
		@friend = Friend.find(params["id"])
		@friend.destroy
		redirect_to friends_path
	end 

	private
	  def friend_params
	    params.require(:friend).permit(:firstName, :surname, :location)
	  end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
   
  WEATHER_API_KEY = '32a40352b94f9f112f73bc2f2cd13765'
  WEATHER_BASE_URL = 'http://api.openweathermap.org/data/2.5/weather'

  def show
  	friends = Friend.find params['friends_id']
  	@friendsWeather = Array.new 
  	hydra = Typhoeus::Hydra.new
  	friends.each do |friend|
  		location = CGI.escape friend['location']
		weatherApiUrl = WEATHER_BASE_URL + "?q=" + location + "&appid=" + WEATHER_API_KEY + "&units=metric"
  		request = Typhoeus::Request.new weatherApiUrl
    	request.on_complete do |response|
      	jsonResponse = JSON.parse response.body
        temperature = jsonResponse['main']['temp']
  			weatherDescription = jsonResponse['weather'][0]['description'].downcase
  			weatherIcon = jsonResponse['weather'][0]['icon']
  			friendAsHash = friend.attributes
  			friendAsHash ['temperature'] = temperature
  			friendAsHash ['weatherDescription'] = weatherDescription
  			friendAsHash ['weatherIcon'] = weatherIcon
  			@friendsWeather.push friendAsHash	
    	end

  		hydra.queue request
  	end
  	hydra.run
   	 

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/friends/edit.html.erb
<div class="container">
	<h4>Edit Friend</h4>

	<%= form_for @friend, url: friend_path, method: 'PATCH' do |f| %>
	  
	    <%= f.label :firstName %>
	    <%= f.text_field :firstName %>

	    <%= f.label :surname %>
	    <%= f.text_field :surname %>

	    <%= f.label :location %>
	    <%= f.text_field :location %>
 		<br>
	    <%= f.submit %>
	<% end %>
</div>

app/views/friends/index.html.erb
<div class="container">
 
	<h4>Friend's list</h4>

	<%= link_to 'Add New Friend', new_friend_path %>

	<%= form_for :friends, url: weather_path, method: 'GET' do |f| %>
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Location</th>
					<th colspan="3"/>
				</tr>
			</thead>
			<tbody>
			<% @friends.each do |friend| %>
				<tr>
					<td><%= friend.firstName %> <%= friend.surname %></td>
					<td><%= friend.location %></td>
					<td><input type="checkbox" name='friends_id[]' value=<%=friend.id%>></td>
					<td><%= link_to 'Edit', edit_friend_path(friend) %></td>
					<td><%= link_to 'Delete', friend_path(friend), method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			 <% end %>
		 	</tbody>
		</table> 
		 <input type="submit" value="Compare Weather">

	<% end %>
	

</div>

app/views/friends/new.html.erb
<div class="container">
	<h4>New Friend</h4>

	<%= form_for :friend, url: friends_path do |f| %>
	  
	    <%= f.label :firstName %>
	    <%= f.text_field :firstName %>

	    <%= f.label :surname %>
	    <%= f.text_field :surname %>

	    <%= f.label :location %>
	    <%= f.text_field :location %>
 		<br>
	    <%= f.submit %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FriendsWeather</title>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Raleway:400,300,600' ,media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weather/show.html.erb
<div class="container">

	<h4>Show the weather</h4>
	
	<table>
		<thead>
			<tr>
				<th>Name</th>
				<th>Location</th>
				<th>Weather</th>
				<th/>
			</tr>
		</thead>
		<tbody>
		<% @friendsWeather.each do |friendWeather| %>
			<tr>
				<td><%= friendWeather['firstName'] %> <%= friendWeather['surname'] %></td>
				<td><%= friendWeather['location'] %></td>
				<td><%= friendWeather['temperature'] %>°C - <%= friendWeather['weatherDescription'] %></td>
				<td><img src="http://openweathermap.org/img/w/<%= friendWeather['weatherIcon'] %>.png"></td>
			</tr>
		<% end %> 
	 	</tbody>
	</table>

</div>